### ISSUE TITLE
Implement JSON API

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#4]
Implement according to specification:
http://docs.accountrestapi.apiary.io

### sign in, check session, sign out
- [x] PUT /session
- [x] GET /session
- [x] DELETE /session

### sign up, get / update / destroy account
- [x] PUT /session/account
- [x] GET /session/account
- [x] DELETE /session/account

### get / update profile
- [x] #11  – GET /session/account/profile 
- [x] #11  – PATCH /session/account/profile

### requests (e.g. password resets / username reminder, user account confirmation)
- [x] #30 – POST /requests
- [ ] #10 – GET /requests (admins only)
- [ ] #10 – GET /requests/{id}
- [ ] #10 – DELETE /requests/{id}

### admins only: manage accounts
- [x] #12 – POST /accounts
- [x] #12 – GET /accounts
- [x] #12 – GET /accounts/{username}
- [x] #12 – PATCH /accounts/{username}
- [x] #12 – DELETE /accounts/{username}

**Comment by gr2m** [comment]
remaining issue is #10, closing this one
